# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emali',
            new_name='email',
        ),
    ]
