# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0002_auto_20160414_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='head_image',
            field=models.FileField(upload_to='./upload'),
        ),
    ]
