# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0003_auto_20160415_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votes.User'),
        ),
    ]
