# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0005_auto_20160415_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='votessystem',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
