# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-15 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0006_votessystem_total_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='exmaple@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.CharField(default='This guy is lazy that what also did not leave here.', max_length=400),
        ),
    ]
