# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0007_auto_20160415_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='ip',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
