# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0008_auto_20160416_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='votessystem',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='head_image',
            field=models.FileField(default='Bus.png', upload_to='./upload'),
        ),
    ]
