# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0009_auto_20160416_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeuser',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='user',
        ),
    ]
