# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0010_auto_20160416_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeuser',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Votes.User'),
        ),
    ]
