# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0011_auto_20160417_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeuser',
            old_name='username',
            new_name='user',
        ),
    ]
