# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0013_auto_20160417_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeuser',
            name='username',
        ),
        migrations.AddField(
            model_name='activeuser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Votes.User'),
            preserve_default=False,
        ),
    ]
