# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 13:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0015_auto_20160417_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votessystem',
            options={'ordering': ['published_date']},
        ),
        migrations.AddField(
            model_name='votessystem',
            name='published_date',
            field=models.DateField(default=datetime.date),
        ),
    ]
