# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0016_auto_20160421_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votessystem',
            name='published_date',
            field=models.DateField(),
        ),
    ]
