# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-21 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Votes', '0018_auto_20160421_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votessystem',
            name='published_date',
        ),
    ]
