# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_author_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authours',
            new_name='authors',
        ),
    ]
