# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20160305_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbs_user',
            name='email',
            field=models.CharField(default=b'exmaple@exm.com', max_length=30),
        ),
    ]
