# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 17:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('limit_time', models.PositiveIntegerField(default=1)),
                ('limit_memory', models.PositiveIntegerField(default=134217728)),
                ('answer_lang', models.PositiveSmallIntegerField(choices=[(0, 'NONE'), (1, 'C'), (2, 'C++'), (3, 'Java'), (4, 'Python'), (5, 'Pascal'), (6, 'FORTRAN')], default=0)),
                ('title', models.CharField(max_length=254)),
                ('content', models.TextField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('source', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('lang', models.PositiveSmallIntegerField(choices=[(0, 'NONE'), (1, 'C'), (2, 'C++'), (3, 'Java'), (4, 'Python'), (5, 'Pascal'), (6, 'FORTRAN')])),
                ('status', models.SmallIntegerField(choices=[(0, 'Accepted'), (1, 'Waiting'), (2, 'Compiling'), (3, 'Running'), (-1, 'Compilation Error'), (-2, 'Syntax Error'), (-3, 'Runtime Error'), (-4, 'Output Limit Exceeded'), (-5, 'Time Limit Exceeded'), (-6, 'Memory Limit Exceeded'), (-7, 'Wrong Answer'), (-8, 'Presentation Error')], default=1)),
                ('run_time', models.PositiveSmallIntegerField(null=True)),
                ('run_memory', models.PositiveIntegerField(null=True)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.Problem')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sample', models.BooleanField(default=False)),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.Problem')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('school', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='testcase',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submit',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='OJ.Problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
