# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['published_time']},
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='time',
            new_name='published_time',
        ),
    ]
