# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0002_auto_20160429_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(max_length=500)),
                ('click_num', models.IntegerField(default=0)),
                ('click_like', models.IntegerField(default=0)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.Problem')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.UserInfo')),
            ],
        ),
        migrations.AlterModelOptions(
            name='submit',
            options={'ordering': ['-time']},
        ),
    ]
