# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_auto_20160429_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discuss',
            old_name='click_like',
            new_name='like',
        ),
    ]
