# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 05:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0006_auto_20160429_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterModelOptions(
            name='discuss',
            options={'ordering': ['date']},
        ),
        migrations.AddField(
            model_name='discuss',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 4, 30, 5, 25, 29, 308743, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
