# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 07:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBS_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(default='This guy is too lazy to three is emtpy.', max_length=200)),
                ('postings', models.IntegerField(default=0)),
                ('phone', models.ImageField(default='/upload/init.png', upload_to='/upload')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.BBS_User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summer', models.CharField(max_length=500)),
                ('context', models.TextField(max_length=2000)),
                ('date_time', models.DateTimeField()),
                ('votes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.BBS_User')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='posting_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.Posting'),
        ),
    ]
