# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 08:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBSUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(default='This guy is too lazy to three is emtpy.', max_length=200)),
                ('postings', models.IntegerField(default=0)),
                ('phone', models.ImageField(default='home/royecode/Programming/python/django/BBS/APP/favicon.ico', upload_to='home/royecode/Programming/python/django/BBS/APP/upload')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bbs_user',
            name='name',
        ),
        migrations.AlterField(
            model_name='category',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.BBSUser'),
        ),
        migrations.AlterField(
            model_name='posting',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.BBSUser'),
        ),
        migrations.DeleteModel(
            name='BBS_User',
        ),
    ]
